// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomScheduling.Infrastructure.Context;

#nullable disable

namespace RoomScheduling.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomScheduling.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@ictu.edu.vn",
                            HoTen = "Trần Quản Trị",
                            Khoa = "CNTT",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$RZf9vvbDMOv5FdB0HJArF.vSg..5xx5GwWCSxjy7Sp5EuikjIaj.G",
                            Role = "Admin",
                            SoDienThoai = "",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "chien@ictu.edu.vn",
                            HoTen = "Nguyễn Văn Chiến",
                            Khoa = "CNTT",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$Xg1o3NUrrVa99TBpgtoqhu4HCQezo.qzJh2opo/RBaCH6z7n4xbV.",
                            Role = "User",
                            SoDienThoai = "",
                            Username = "chien"
                        },
                        new
                        {
                            Id = 3,
                            Email = "huong@ictu.edu.vn",
                            HoTen = "Lê Thị Hương",
                            Khoa = "CNTT",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$Xg1o3NUrrVa99TBpgtoqhu4HCQezo.qzJh2opo/RBaCH6z7n4xbV.",
                            Role = "User",
                            SoDienThoai = "",
                            Username = "huong"
                        },
                        new
                        {
                            Id = 4,
                            Email = "minh@ictu.edu.vn",
                            HoTen = "Phạm Tuấn Minh",
                            Khoa = "KTCNS",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$Xg1o3NUrrVa99TBpgtoqhu4HCQezo.qzJh2opo/RBaCH6z7n4xbV.",
                            Role = "User",
                            SoDienThoai = "",
                            Username = "minh"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lan@ictu.edu.vn",
                            HoTen = "Ngô Thị Lan",
                            Khoa = "KTCNS",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$Xg1o3NUrrVa99TBpgtoqhu4HCQezo.qzJh2opo/RBaCH6z7n4xbV.",
                            Role = "User",
                            SoDienThoai = "",
                            Username = "lan"
                        },
                        new
                        {
                            Id = 6,
                            Email = "thanh@ictu.edu.vn",
                            HoTen = "Vũ Đức Thành",
                            Khoa = "MTTB",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$Xg1o3NUrrVa99TBpgtoqhu4HCQezo.qzJh2opo/RBaCH6z7n4xbV.",
                            Role = "User",
                            SoDienThoai = "",
                            Username = "thanh"
                        },
                        new
                        {
                            Id = 7,
                            Email = "giang@ictu.edu.vn",
                            HoTen = "Đinh Thị Giang",
                            Khoa = "MTTB",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$Xg1o3NUrrVa99TBpgtoqhu4HCQezo.qzJh2opo/RBaCH6z7n4xbV.",
                            Role = "User",
                            SoDienThoai = "",
                            Username = "giang"
                        },
                        new
                        {
                            Id = 8,
                            Email = "hung@ictu.edu.vn",
                            HoTen = "Bùi Văn Hùng",
                            Khoa = "KTQTS",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$Xg1o3NUrrVa99TBpgtoqhu4HCQezo.qzJh2opo/RBaCH6z7n4xbV.",
                            Role = "User",
                            SoDienThoai = "",
                            Username = "hung"
                        },
                        new
                        {
                            Id = 9,
                            Email = "phuong@ictu.edu.vn",
                            HoTen = "Hoàng Minh Phương",
                            Khoa = "KTQTS",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$Xg1o3NUrrVa99TBpgtoqhu4HCQezo.qzJh2opo/RBaCH6z7n4xbV.",
                            Role = "User",
                            SoDienThoai = "",
                            Username = "phuong"
                        },
                        new
                        {
                            Id = 10,
                            Email = "quang@ictu.edu.vn",
                            HoTen = "Trịnh Quang Khải",
                            Khoa = "CNTT",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2b$10$Xg1o3NUrrVa99TBpgtoqhu4HCQezo.qzJh2opo/RBaCH6z7n4xbV.",
                            Role = "User",
                            SoDienThoai = "",
                            Username = "quang"
                        });
                });

            modelBuilder.Entity("RoomScheduling.Domain.Entities.Phong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KhoaQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaThietBi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Phongs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KhoaQuanLy = "CNTT",
                            MoTaThietBi = "30 máy tính, máy chiếu, điều hòa",
                            SucChua = 30,
                            Ten = "Phòng Lab IT-01"
                        },
                        new
                        {
                            Id = 2,
                            KhoaQuanLy = "CNTT",
                            MoTaThietBi = "Màn hình LED, bảng trắng, điều hòa",
                            SucChua = 20,
                            Ten = "Phòng Seminar IT-02"
                        },
                        new
                        {
                            Id = 3,
                            KhoaQuanLy = "CNTT",
                            MoTaThietBi = "Máy tính, server thực hành, switch mạng",
                            SucChua = 25,
                            Ten = "Phòng Thực hành IT-03"
                        },
                        new
                        {
                            Id = 4,
                            KhoaQuanLy = "CNTT",
                            MoTaThietBi = "Máy chiếu 4K, âm thanh, mic không dây",
                            SucChua = 50,
                            Ten = "Phòng Hội thảo IT-04"
                        },
                        new
                        {
                            Id = 5,
                            KhoaQuanLy = "CNTT",
                            MoTaThietBi = "TV 65 inch, webcam, bảng flip chart",
                            SucChua = 10,
                            Ten = "Phòng Họp nhỏ IT-05"
                        },
                        new
                        {
                            Id = 6,
                            KhoaQuanLy = "KTCNS",
                            MoTaThietBi = "Bàn thực hành điện tử, máy chiếu, điều hòa",
                            SucChua = 25,
                            Ten = "Phòng Lab KTS-01"
                        },
                        new
                        {
                            Id = 7,
                            KhoaQuanLy = "KTCNS",
                            MoTaThietBi = "Màn hình tương tác, webcam hội nghị",
                            SucChua = 20,
                            Ten = "Phòng Seminar KTS-02"
                        },
                        new
                        {
                            Id = 8,
                            KhoaQuanLy = "KTCNS",
                            MoTaThietBi = "Kit Arduino, Raspberry Pi, sensor",
                            SucChua = 15,
                            Ten = "Phòng IoT KTS-03"
                        },
                        new
                        {
                            Id = 9,
                            KhoaQuanLy = "KTCNS",
                            MoTaThietBi = "Âm thanh hội trường, máy chiếu, mic không dây",
                            SucChua = 40,
                            Ten = "Phòng Hội thảo KTS-04"
                        },
                        new
                        {
                            Id = 10,
                            KhoaQuanLy = "KTCNS",
                            MoTaThietBi = "TV, webcam, bảng trắng",
                            SucChua = 12,
                            Ten = "Phòng Họp KTS-05"
                        },
                        new
                        {
                            Id = 11,
                            KhoaQuanLy = "MTTB",
                            MoTaThietBi = "Phông xanh, đèn studio, máy ảnh DSLR",
                            SucChua = 20,
                            Ten = "Phòng Studio MT-01"
                        },
                        new
                        {
                            Id = 12,
                            KhoaQuanLy = "MTTB",
                            MoTaThietBi = "20 PC đồ họa, bảng vẽ Wacom, máy in màu",
                            SucChua = 20,
                            Ten = "Phòng Thiết kế MT-02"
                        },
                        new
                        {
                            Id = 13,
                            KhoaQuanLy = "MTTB",
                            MoTaThietBi = "Workstation video, Premiere, After Effects",
                            SucChua = 15,
                            Ten = "Phòng Dựng phim MT-03"
                        },
                        new
                        {
                            Id = 14,
                            KhoaQuanLy = "MTTB",
                            MoTaThietBi = "Máy chiếu, bảng trắng, hệ thống trình chiếu",
                            SucChua = 30,
                            Ten = "Phòng Báo chí MT-04"
                        },
                        new
                        {
                            Id = 15,
                            KhoaQuanLy = "MTTB",
                            MoTaThietBi = "TV, bảng brainstorm, ghế sáng tạo",
                            SucChua = 10,
                            Ten = "Phòng Thảo luận MT-05"
                        },
                        new
                        {
                            Id = 16,
                            KhoaQuanLy = "KTQTS",
                            MoTaThietBi = "Âm thanh hội trường, máy chiếu 6000lm",
                            SucChua = 80,
                            Ten = "Phòng Hội thảo KT-01"
                        },
                        new
                        {
                            Id = 17,
                            KhoaQuanLy = "KTQTS",
                            MoTaThietBi = "Màn hình TV, webcam 4K, bảng flip chart",
                            SucChua = 20,
                            Ten = "Phòng Họp KT-02"
                        },
                        new
                        {
                            Id = 18,
                            KhoaQuanLy = "KTQTS",
                            MoTaThietBi = "30 máy tính, phần mềm kế toán, Excel",
                            SucChua = 30,
                            Ten = "Phòng Lab KT-03"
                        },
                        new
                        {
                            Id = 19,
                            KhoaQuanLy = "KTQTS",
                            MoTaThietBi = "Bảng trắng, màn chiếu, wifi tốc độ cao",
                            SucChua = 15,
                            Ten = "Phòng Thảo luận KT-04"
                        },
                        new
                        {
                            Id = 20,
                            KhoaQuanLy = "KTQTS",
                            MoTaThietBi = "Bàn họp executive, TV 85 inch, hội nghị xa",
                            SucChua = 8,
                            Ten = "Phòng VIP KT-05"
                        });
                });

            modelBuilder.Entity("RoomScheduling.Domain.Entities.ThamGiaCuocHop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("LaChuTri")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("YeuCauDatPhongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThamGiaCuocHops");
                });

            modelBuilder.Entity("RoomScheduling.Domain.Entities.ThietBi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.ToTable("ThietBis");
                });

            modelBuilder.Entity("RoomScheduling.Domain.Entities.YeuCauDatPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChuAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCheckedIn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("NguoiDat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<string>("RecurringGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.HasIndex("StartTime", "EndTime", "PhongId", "TrangThai");

                    b.ToTable("YeuCauDatPhongs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2026, 2, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Nguyễn Văn Chiến",
                            PhongId = 1,
                            StartTime = new DateTime(2026, 2, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2026, 2, 12, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Nguyễn Văn Chiến",
                            PhongId = 3,
                            StartTime = new DateTime(2026, 2, 12, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2026, 2, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Nguyễn Văn Chiến",
                            PhongId = 5,
                            StartTime = new DateTime(2026, 2, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new DateTime(2026, 2, 18, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Nguyễn Văn Chiến",
                            PhongId = 2,
                            StartTime = new DateTime(2026, 2, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new DateTime(2026, 2, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Nguyễn Văn Chiến",
                            PhongId = 1,
                            StartTime = new DateTime(2026, 2, 20, 7, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new DateTime(2026, 2, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Nguyễn Văn Chiến",
                            PhongId = 4,
                            StartTime = new DateTime(2026, 2, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 7,
                            EndTime = new DateTime(2026, 2, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Lê Thị Hương",
                            PhongId = 2,
                            StartTime = new DateTime(2026, 2, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 8,
                            EndTime = new DateTime(2026, 2, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Lê Thị Hương",
                            PhongId = 4,
                            StartTime = new DateTime(2026, 2, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 9,
                            EndTime = new DateTime(2026, 2, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Lê Thị Hương",
                            PhongId = 5,
                            StartTime = new DateTime(2026, 2, 16, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 10,
                            EndTime = new DateTime(2026, 2, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Lê Thị Hương",
                            PhongId = 1,
                            StartTime = new DateTime(2026, 2, 19, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 11,
                            EndTime = new DateTime(2026, 2, 22, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Lê Thị Hương",
                            PhongId = 3,
                            StartTime = new DateTime(2026, 2, 22, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 12,
                            EndTime = new DateTime(2026, 2, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Lê Thị Hương",
                            PhongId = 2,
                            StartTime = new DateTime(2026, 2, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 13,
                            EndTime = new DateTime(2026, 2, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Phạm Tuấn Minh",
                            PhongId = 6,
                            StartTime = new DateTime(2026, 2, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 14,
                            EndTime = new DateTime(2026, 2, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Phạm Tuấn Minh",
                            PhongId = 8,
                            StartTime = new DateTime(2026, 2, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 15,
                            EndTime = new DateTime(2026, 2, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Phạm Tuấn Minh",
                            PhongId = 9,
                            StartTime = new DateTime(2026, 2, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 16,
                            EndTime = new DateTime(2026, 2, 18, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Phạm Tuấn Minh",
                            PhongId = 7,
                            StartTime = new DateTime(2026, 2, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 17,
                            EndTime = new DateTime(2026, 2, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Phạm Tuấn Minh",
                            PhongId = 6,
                            StartTime = new DateTime(2026, 2, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 18,
                            EndTime = new DateTime(2026, 2, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Phạm Tuấn Minh",
                            PhongId = 10,
                            StartTime = new DateTime(2026, 2, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 19,
                            EndTime = new DateTime(2026, 2, 11, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Ngô Thị Lan",
                            PhongId = 7,
                            StartTime = new DateTime(2026, 2, 11, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 20,
                            EndTime = new DateTime(2026, 2, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Ngô Thị Lan",
                            PhongId = 8,
                            StartTime = new DateTime(2026, 2, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 21,
                            EndTime = new DateTime(2026, 2, 17, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Ngô Thị Lan",
                            PhongId = 9,
                            StartTime = new DateTime(2026, 2, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 22,
                            EndTime = new DateTime(2026, 2, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Ngô Thị Lan",
                            PhongId = 6,
                            StartTime = new DateTime(2026, 2, 20, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 23,
                            EndTime = new DateTime(2026, 2, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Ngô Thị Lan",
                            PhongId = 9,
                            StartTime = new DateTime(2026, 2, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 24,
                            EndTime = new DateTime(2026, 2, 25, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Ngô Thị Lan",
                            PhongId = 10,
                            StartTime = new DateTime(2026, 2, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 25,
                            EndTime = new DateTime(2026, 2, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Vũ Đức Thành",
                            PhongId = 11,
                            StartTime = new DateTime(2026, 2, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 26,
                            EndTime = new DateTime(2026, 2, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Vũ Đức Thành",
                            PhongId = 12,
                            StartTime = new DateTime(2026, 2, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 27,
                            EndTime = new DateTime(2026, 2, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Vũ Đức Thành",
                            PhongId = 13,
                            StartTime = new DateTime(2026, 2, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 28,
                            EndTime = new DateTime(2026, 2, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Vũ Đức Thành",
                            PhongId = 14,
                            StartTime = new DateTime(2026, 2, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 29,
                            EndTime = new DateTime(2026, 2, 21, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Vũ Đức Thành",
                            PhongId = 11,
                            StartTime = new DateTime(2026, 2, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 30,
                            EndTime = new DateTime(2026, 2, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Vũ Đức Thành",
                            PhongId = 12,
                            StartTime = new DateTime(2026, 2, 24, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 31,
                            EndTime = new DateTime(2026, 2, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Đinh Thị Giang",
                            PhongId = 13,
                            StartTime = new DateTime(2026, 2, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 32,
                            EndTime = new DateTime(2026, 2, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Đinh Thị Giang",
                            PhongId = 11,
                            StartTime = new DateTime(2026, 2, 13, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 33,
                            EndTime = new DateTime(2026, 2, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Đinh Thị Giang",
                            PhongId = 15,
                            StartTime = new DateTime(2026, 2, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 34,
                            EndTime = new DateTime(2026, 2, 19, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Đinh Thị Giang",
                            PhongId = 12,
                            StartTime = new DateTime(2026, 2, 19, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 35,
                            EndTime = new DateTime(2026, 2, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Đinh Thị Giang",
                            PhongId = 14,
                            StartTime = new DateTime(2026, 2, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 36,
                            EndTime = new DateTime(2026, 2, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Đinh Thị Giang",
                            PhongId = 13,
                            StartTime = new DateTime(2026, 2, 25, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 37,
                            EndTime = new DateTime(2026, 2, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Bùi Văn Hùng",
                            PhongId = 17,
                            StartTime = new DateTime(2026, 2, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 38,
                            EndTime = new DateTime(2026, 2, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Bùi Văn Hùng",
                            PhongId = 18,
                            StartTime = new DateTime(2026, 2, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 39,
                            EndTime = new DateTime(2026, 2, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Bùi Văn Hùng",
                            PhongId = 16,
                            StartTime = new DateTime(2026, 2, 17, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 40,
                            EndTime = new DateTime(2026, 2, 19, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Bùi Văn Hùng",
                            PhongId = 20,
                            StartTime = new DateTime(2026, 2, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 41,
                            EndTime = new DateTime(2026, 2, 21, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Bùi Văn Hùng",
                            PhongId = 19,
                            StartTime = new DateTime(2026, 2, 21, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 42,
                            EndTime = new DateTime(2026, 2, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Bùi Văn Hùng",
                            PhongId = 18,
                            StartTime = new DateTime(2026, 2, 24, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 43,
                            EndTime = new DateTime(2026, 2, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Hoàng Minh Phương",
                            PhongId = 16,
                            StartTime = new DateTime(2026, 2, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 44,
                            EndTime = new DateTime(2026, 2, 14, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Hoàng Minh Phương",
                            PhongId = 17,
                            StartTime = new DateTime(2026, 2, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 45,
                            EndTime = new DateTime(2026, 2, 16, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Hoàng Minh Phương",
                            PhongId = 19,
                            StartTime = new DateTime(2026, 2, 16, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 46,
                            EndTime = new DateTime(2026, 2, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Hoàng Minh Phương",
                            PhongId = 18,
                            StartTime = new DateTime(2026, 2, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 47,
                            EndTime = new DateTime(2026, 2, 23, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Hoàng Minh Phương",
                            PhongId = 20,
                            StartTime = new DateTime(2026, 2, 23, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 48,
                            EndTime = new DateTime(2026, 2, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Hoàng Minh Phương",
                            PhongId = 17,
                            StartTime = new DateTime(2026, 2, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 49,
                            EndTime = new DateTime(2026, 2, 12, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Trịnh Quang Khải",
                            PhongId = 1,
                            StartTime = new DateTime(2026, 2, 12, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 50,
                            EndTime = new DateTime(2026, 2, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Trịnh Quang Khải",
                            PhongId = 4,
                            StartTime = new DateTime(2026, 2, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 51,
                            EndTime = new DateTime(2026, 2, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Trịnh Quang Khải",
                            PhongId = 3,
                            StartTime = new DateTime(2026, 2, 17, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 52,
                            EndTime = new DateTime(2026, 2, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Trịnh Quang Khải",
                            PhongId = 2,
                            StartTime = new DateTime(2026, 2, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 53,
                            EndTime = new DateTime(2026, 2, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Trịnh Quang Khải",
                            PhongId = 5,
                            StartTime = new DateTime(2026, 2, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 54,
                            EndTime = new DateTime(2026, 2, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Trịnh Quang Khải",
                            PhongId = 4,
                            StartTime = new DateTime(2026, 2, 25, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 55,
                            EndTime = new DateTime(2026, 2, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Nguyễn Văn Chiến",
                            PhongId = 16,
                            StartTime = new DateTime(2026, 2, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 56,
                            EndTime = new DateTime(2026, 2, 27, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Phạm Tuấn Minh",
                            PhongId = 12,
                            StartTime = new DateTime(2026, 2, 27, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 57,
                            EndTime = new DateTime(2026, 2, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Bùi Văn Hùng",
                            PhongId = 1,
                            StartTime = new DateTime(2026, 2, 28, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 58,
                            EndTime = new DateTime(2026, 3, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Đinh Thị Giang",
                            PhongId = 9,
                            StartTime = new DateTime(2026, 3, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 59,
                            EndTime = new DateTime(2026, 3, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Ngô Thị Lan",
                            PhongId = 4,
                            StartTime = new DateTime(2026, 3, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 60,
                            EndTime = new DateTime(2026, 3, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCheckedIn = false,
                            IsRecurring = false,
                            NguoiDat = "Lê Thị Hương",
                            PhongId = 20,
                            StartTime = new DateTime(2026, 3, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("RoomScheduling.Domain.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiNhanId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("RoomScheduling.Domain.Entities.ThietBi", b =>
                {
                    b.HasOne("RoomScheduling.Domain.Entities.Phong", "Phong")
                        .WithMany("ThietBis")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("RoomScheduling.Domain.Entities.YeuCauDatPhong", b =>
                {
                    b.HasOne("RoomScheduling.Domain.Entities.Phong", "Phong")
                        .WithMany("DanhSachYeuCau")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("RoomScheduling.Domain.Entities.Phong", b =>
                {
                    b.Navigation("DanhSachYeuCau");

                    b.Navigation("ThietBis");
                });
#pragma warning restore 612, 618
        }
    }
}
